---
kind: pipeline
type: docker
name: hydra-identity-manager-server-build

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.pkg.github.com/wlp2s0/hydra-identity-manager-server/server
      context: .
      dockerfile: ./.docker/Dockerfile
      registry: docker.pkg.github.com
      auto_tag: true
      target: production

trigger:
  event:
  - tag
  - promote
  - rollback
#---

#kind: pipeline
#type: ssh
#name: hydra-identity-manager-server-deploy
#
#server:
#  host:
#    from_secret: host
#  user:
#    from_secret: user
#  # port:
#  #   from_secret: port
#  ssh_key:
#    from_secret: ssh_key
#
#steps:
#  - name: deploy
#  # environment:
#  #   GITHUB_USERNAME:
#  #     from_secret: github_username
#  #   GITHUB_TOKEN:
#  #     from_secret: github_token
#    commands:
#  #   - docker login https://ghcr.io --username $GITHUB_USERNAME --password $GITHUB_TOKEN
#      - cd /home/cippini/docker/hydra-identity-manager/beta
#      - docker-compose pull && docker-compose up --detach --build api
#
#depends_on:
#  - build
#
#trigger:
#  event:
#    exclude:
#      - promote
#      - rollback